CREATE TABLE IF NOT EXISTS CAMPAINGS
    (id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    status INT NOT NULL,
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    end_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);

CREATE TABLE IF NOT EXISTS ADS
(id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
 name VARCHAR(255) NOT NULL,
 status INT NOT NULL,
 platforms ARRAY NOT NULL,
 assert_url VARCHAR(255) NOT NULL,
 campaings INT NOT NULL,
 FOREIGN KEY (campaings) REFERENCES CAMPAINGS(id) ON DELETE CASCADE ON UPDATE CASCADE);