CREATE TABLE IF NOT EXISTS ADS
(id INTEGER PRIMARY KEY,
 name VARCHAR(255) NOT NULL,
 status INTEGER NOT NULL,
 platforms ARRAY NOT NULL,
 assert_url VARCHAR(255) NOT NULL);

CREATE TABLE IF NOT EXISTS CAMPAINGS
    (id INTEGER PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    status INTEGER NOT NULL,
    start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    end_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (id) REFERENCES ADS(id));